# Generated by Django 3.0.8 on 2020-08-02 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('temperature', models.FloatField(max_length=10)),
                ('image', models.ImageField(default='', height_field=20, upload_to='weather/', width_field=20)),
            ],
        ),
    ]
