# Generated by Django 3.0.8 on 2020-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20200802_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='temperature',
            field=models.FloatField(default=0.0, max_length=20),
        ),
    ]
