# Generated by Django 3.0.8 on 2020-08-06 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200804_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.CharField(default='', max_length=100),
        ),
    ]
