# Generated by Django 3.0.8 on 2020-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20200806_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='condition',
            field=models.CharField(default='', max_length=20),
        ),
    ]
